### PR TITLE
Replace Rich Quotations with Standard Text

### PR DESCRIPTION
**Pull request by SeanKilleen**
Quotations in markdown files here are often represented as `“` and `”`.

In this PR, I replace them both with `"`.

### CODE REVIEW

**Comment by sean-gilliam** [comment]
After merging your PR #213, there are some conflicts in this branch. If you could fix these up, that would be great :)

**Comment by SeanKilleen** [comment]
@sean-gilliam no problem, will get it done ASAP.

**Comment by SeanKilleen** [comment]
Wow, and by "ASAP" I mean "this fell off my radar entirely and I'm very sorry" :)

**Comment by sean-gilliam** [comment]
lol no worries.

**Pull request merged**
