### PR TITLE
Working with Actors. Initial outline

### PR DESCRIPTION
**Pull request by Danthar**
**changes**
- Copied various sections from the Working with actors document to
  separate documents (but kept the original document intact)
- Moved all parts concerning ReceiveActor API from the ReceiveActor.md
  to a separate document (Defining an actor class).
- Removed the ReceiveActor document because the remaining stuff
  detailing the Become API are explained elsewhere as well.
- Creating actors document is missing the F# example. The current F#
  document has so many stuff in there.. and since im not an F# dev, im
  uncertain whats relevant for the `Creating actors` document, and whats
  not. So im leaving that for someone else to fill in.
- Creating actors document contains a segment about the Inbox. Don't
  think it belongs there, but im not sure where to put it.
- What's in an Actor document. The outline is there, but im not sure
  what to put in there so I put in TODO's
- ActorRefs and ActorSelections document. The outline is there. Alot of this stuff is talked about in the concepts section. So unsure what to put in here.
- creating-actors-with-props. The outline is there.
- handling-messages. The outline is there. But im unsure what to put in
  there. Receive Actor API and UntypedActor API are described elsewhere as
  well.
- Sending messages document. Copied the contents from the 'Send
  messages' section in the Working with actors document
- After reviewing the 'defining-an-actor' document: After all the changes the 'UntypedActor API 'chapter is of poor quality. It needs at the very least some of the examples and stuff back in there. 

This PR is a meant to be a starting point. There is alot that still needs to be done. But at least this makes it easier for individual contributors to pick and chose topics and chapters and do some work on that.

As you can tell, alot of the chapters are still empty. What I need right now is feedback.
- Feedback on what should go in the various chapters that are still empty, so that we can provide a better description on what we expect there. Or even better: Provide the actual text that needs to go there :P 
- Feedback on how we should proceed from here. This PR introduces a whole new unfinished/in-progress section in the docs. Are we OK with that? Or are we going to improve this PR first before we merge it in?

### CODE REVIEW

**Comment by sean-gilliam** [comment]
:+1: for starting on the gordian knot that is #7. 

Noticed a few small things:
- Line items under "Working with Actors" appear to run together instead of a list. Just a markdown issue really. Just need to add a space between each dash and open bracket, e.g.
  `- [Creating your first Actor]` instead of `-[Creating your first Actor]`
- Dispatchers, Mailboxes, Switchable Behaviors, Stashing Messages, and Routers were moved to the working-with-actors directory but the index.md file still has them listed under the Actors heading instead of the Working with Actors heading as outlined in #7.
- I'd personally remove the ReceiveActor --REMOVED entry in index.md
- Like you I'm not sure how upper management likes the idea of a bunch of todo's in the documents. But we do have quite a few of them in there already. So /shrug.

Other than that LGTM :)

**Comment by Aaronontheweb** [comment]
> Like you I'm not sure how upper management likes the idea of a bunch of todo's in the documents. 

If it helps other contributors fill in the blanks, then it's a good idea.

@Danthar need anymore feedback? I think @sean-gilliam did a great job IMHO.

**Comment by Danthar** [comment]
Thanks for the feedback @sean-gilliam . Ill work on the points you outlined and cleanup the PR abit more. Ill probably do that later today, or tomorrow. After that ill give you guys a heads up. So that we can get this in.

**Comment by skotzko** [comment]
I just wanted to chime in and say big thanks to you @Danthar for getting this process started. #7 is a doozie.

**Comment by Danthar** [comment]
Ok, so I cleaned up some stuff. As I was going over things I noticed more stuff that could be done (funny how that works :P). But ill leave that for a separate PR. Got to start somewhere right?

**Pull request merged**
